# Generated by Django 4.0.1 on 2022-01-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_alter_chat_participant_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-time_created',)},
        ),
    ]
