# Generated by Django 4.0.1 on 2022-01-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='owner_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
